# general settings
name: GaussianColorDenoising_CGNetSigma15_t3
model_type: ImageCleanModel
scale: 1
num_gpu: 8  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_GaussianDenoising
    sigma_type: constant
    sigma_range: 15
    in_ch: 3    ## RGB image
    dataroot_gt: ./datasets/guassian_noise/train/DFWB
    dataroot_lq: none
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8

    ### -------------Progressive training--------------------------
    mini_batch_sizes: [8,8,8,4,2,2]             # Batch size per gpu   
    iters: [82000, 94000, 78000, 56000, 36000, 24000]
    gt_size: 384   # Max patch size for progressive training
    gt_sizes: [128,160,192,256,320,384]  # Patch sizes for progressive training.
    ### ------------------------------------------------------------

    ### ------- Training on single fixed-patch size 128x128---------
    # mini_batch_sizes: [8]   
    # iters: [300000]
    # gt_size: 256  
    # gt_sizes: [256]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_GaussianDenoising
    sigma_test: 15
    in_ch: 3  ## RGB image
    dataroot_gt: ./datasets/guassian_noise/test/CBSD68
    dataroot_lq: none
    io_backend:
      type: disk

# network structures
network_g:
  type: CascadedGazeNetBig
  width: 70
  enc_blk_nums: [4, 4, 6, 8]
  middle_blk_num: 10
  dec_blk_nums: [2, 2, 2, 4]
  GCE_CONVS_nums: [4,4,3,3]

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 400000
  warmup_iter: -1 # no warm up
  use_grad_clip: true


  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [82000, 318000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]   
  
  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.9]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 8
  val_freq: !!float 1e3
  save_img: false
  rgb2bgr: true
  use_image: false
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
